# Generated by Django 5.0.6 on 2025-01-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resort',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('locality', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('land_mark', models.CharField(max_length=100)),
                ('parking', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100)),
                ('image', models.ImageField(upload_to='resort_images/')),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single room', 'Single Room'), ('double room', 'Double Room'), ('special room', 'Special Room')], max_length=100)),
                ('wifi_number', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100)),
                ('tv_number', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=100)),
                ('food', models.CharField(choices=[('free', 'Free'), ('non-free', 'Non-Free')], max_length=100)),
                ('price', models.IntegerField()),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.resort')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('rooms', models.IntegerField()),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField()),
                ('total_days', models.IntegerField()),
                ('booked_amount', models.IntegerField()),
                ('date_of_booking', models.DateField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signup')),
            ],
        ),
    ]
